from __future__ import annotations


UI_TEXT: dict[str, dict[str, str]] = {
    "uk": {
        "calculator": "Калькулятор",
        "database": "База даних",
        "builds": "Збережені збірки",
        "compare": "Порівняння",
        "frame": "Рама",
        "testing": "Перевірка формул",
        "help": "Методика",
        "about": "Про програму",
        "simple_mode": "Простий режим",
        "engineering_mode": "Інженерний режим",
        "simple_intro": "Швидкий підбір силової установки: тільки обов'язкові вхідні дані та ключові результати.",
        "engineering_intro": "Повна інженерна модель: моторні параметри, всі запаси, sweep та графіки навантаження.",
        "calculate": "РОЗРАХУВАТИ",
        "add_compare": "Додати до порівняння",
        "search": "Пошук",
        "import": "Імпортувати",
        "export": "Експортувати propellers.db",
        "basic": "ОСНОВНА КОНФІГУРАЦІЯ",
        "advanced": "ПАРАМЕТРИ ІНЖЕНЕРНОЇ МОДЕЛІ",
        "results": "РЕЗУЛЬТАТИ РОЗРАХУНКУ",
        "warnings": "ПОПЕРЕДЖЕННЯ ТА ОБМЕЖЕННЯ",
        "efficiency": "ЕФЕКТИВНІСТЬ І ОПТИМАЛЬНА ТОЧКА",
        "load_graphs": "ГРАФІКИ НАВАНТАЖЕННЯ",
        "graph_note": "Криві розраховані для 10-100% газу з поточними моделлю, напругою, швидкістю та середовищем. Жовта вертикаль - поточний газ; пунктир - ліміт компонента.",
        "hover_help": "Пояснення параметра з'явиться тут після наведення або фокусування. Кнопка ? відкриває повну довідку.",
        "help_panel": "КОНТЕКСТНА ДОВІДКА",
        "language": "МОВА",
        "units": "ОДИНИЦІ",
        "tooltips": "ПІДКАЗКИ ПРИ НАВЕДЕННІ",
        "configuration_mode": "Режим роботи",
        "database_point_mode": "Відтворити випробування з бази",
        "custom_mode": "Власні параметри",
        "reference_point": "Вихідна характеристика з бази",
        "model": "Модель пропелера",
        "medium": "Середовище",
        "voltage": "Робоча напруга",
        "throttle": "Газ",
        "kv": "KV мотора",
        "speed": "Швидкість потоку",
        "mass": "Повна маса",
        "motors": "Кількість моторів",
        "esc": "Ліміт ESC",
        "battery_type": "Тип батареї",
        "capacity": "Ємність батареї",
        "c_rating": "C-рейтинг батареї",
        "battery_s": "Кількість комірок",
        "rm": "Опір обмотки Rm",
        "i0": "Струм холостого ходу I0",
        "motor_max_current": "Максимальний струм мотора",
        "motor_max_power": "Максимальна потужність мотора",
        "density": "Густина середовища",
        "thrust_card": "ТЯГА",
        "current_card": "СТРУМ",
        "power_card": "ПОТУЖНІСТЬ",
        "total_current_card": "ЗАГАЛЬНИЙ СТРУМ",
        "total_power_card": "ЗАГАЛЬНА ЕЛЕКТРИЧНА ПОТУЖНІСТЬ",
        "thrust_per_motor": "ТЯГА / МОТОР",
        "prop_power_per_motor": "ПОТУЖНІСТЬ ПРОПЕЛЕРА / МОТОР",
        "rpm_card": "ОБЕРТИ",
        "tw_card": "ТЯГООЗБРОЄНІСТЬ",
        "runtime_card": "ЧАС РОБОТИ",
        "esc_margin_card": "ЗАПАС ESC",
        "motor_margin_card": "ЗАПАС МОТОРА",
        "battery_margin_card": "ЗАПАС БАТАРЕЇ",
        "structural_card": "СТРУКТУРНИЙ RPM",
        "confidence_card": "ДОСТОВІРНІСТЬ",
        "evidence_card": "ТИП ДАНИХ",
        "aero_eff": "Аеродинамічна ефективність",
        "system_eff": "Ефективність силової установки",
        "optimum": "Оптимальна точка",
        "no_optimum": "Немає допустимої точки sweep за заданими лімітами.",
        "no_warnings": "Критичних попереджень немає.",
        "simplified": "ОЦІНКА ЗА СПРОЩЕНОЮ МОДЕЛЛЮ",
        "chart_thrust": "Тяга від газу",
        "chart_current": "Струм від газу",
        "chart_power": "Електрична потужність",
        "chart_rpm": "RPM і структурний ліміт",
        "chart_efficiency": "Ефективність від газу",
        "throttle_axis": "Газ, %",
        "thrust_axis": "Тяга",
        "current_axis": "Струм, A",
        "power_axis": "Потужність",
        "rpm_axis": "RPM",
        "efficiency_axis": "Ефективність, %",
        "current_point": "Розрахункова крива",
        "aerodynamic": "Аеродинамічна",
        "powertrain": "Силова установка",
        "esc_limit": "Ліміт ESC",
        "battery_limit": "Ліміт батареї",
        "motor_limit": "Ліміт мотора",
        "structural_limit": "Структурний ліміт",
        "models": "МОДЕЛІ",
        "characteristics": "ХАРАКТЕРИСТИКИ",
        "sources": "ДЖЕРЕЛА",
        "real_tests": "РЕАЛЬНІ ВИПРОБУВАННЯ",
        "prediction_only": "ЛИШЕ ПРОГНОЗ",
        "model_search_placeholder": "Model_ID, початкова назва, виробник, серія або SKU",
        "characteristics_title": "ХАРАКТЕРИСТИКИ ВИБРАНОЇ МОДЕЛІ",
        "point_filter_placeholder": "Фільтр: RPM, J, Ct, Cp, ефективність, клас або початковий файл",
        "original": "Початкова назва",
        "manufacturer": "Виробник",
        "size": "Діаметр x крок",
        "evidence": "Тип даних",
        "points": "Точки",
        "geometry": "Геометрія",
        "source_file": "Початковий файл",
        "class": "Клас",
        "save": "Зберегти збірку",
        "update": "Оновити збірку",
        "save_as": "Зберегти як нову",
        "delete": "Видалити",
        "duplicate": "Дублювати",
        "clear": "Очистити",
        "recommend": "Розрахувати та рекомендувати",
        "custom_build": "КАСТОМНА ЗБІРКА",
        "build_name": "Назва",
        "motor_name": "Мотор",
        "battery_name": "Батарея",
        "esc_name": "ESC",
        "frame_name": "Рама",
        "payload": "Корисне навантаження",
        "description": "Опис",
        "note": "Примітка",
        "build_capture_note": "Пропелер, KV, батарея, ESC, кількість моторів, маса та інженерні параметри беруться з калькулятора.",
        "saved_builds_list": "ЗБЕРЕЖЕНІ ВАРІАНТИ",
        "modules_title": "МОДУЛІ ТА АКСЕСУАРИ ЗБІРКИ",
        "modules_note": "Позначте фактично встановлені модулі, введіть модель, кількість і масу одного. Вони зберігаються у складі збірки; у фізичному розрахунку впливають лише через повну масу апарата.",
        "module_included": "Є",
        "module_type": "Тип",
        "module_model": "Виробник / модель",
        "module_quantity": "К-сть",
        "module_mass_each": "Маса 1 шт.",
        "module_mass_total": "Разом",
        "module_add_other": "Додати інший",
        "module_remove": "Прибрати рядок",
        "module_reset": "Типовий список",
        "module_apply_payload": "Врахувати масу в розрахунку",
        "module_total": "Вибрано модулів: {count}. Загальна маса: {mass} {unit}. Не додавайте цю масу повторно, якщо вона вже входить у повну масу апарата.",
        "module_count": "Модулі",
        "module_mass": "Маса модулів",
        "module_flight_controller": "Польотний контролер / автопілот",
        "module_power_distribution": "PDB / силова плата",
        "module_receiver": "RC-приймач",
        "module_gps": "GPS / GNSS",
        "module_telemetry": "Телеметрія / радіомодем",
        "module_vtx": "Відеопередавач (VTX)",
        "module_antenna": "Антена",
        "module_camera": "Камера",
        "module_gimbal": "Підвіс камери",
        "module_remote_id": "Модуль Remote ID / ідентифікації",
        "module_sensors": "Датчики / сенсори",
        "module_landing_gear": "Шасі",
        "module_wiring": "Проводка, роз'єми, кріплення",
        "module_other": "Інший модуль",
        "export_json": "Експортувати JSON",
        "import_json": "Імпортувати JSON",
        "criterion": "Критерій ранжування",
        "crit_max_thrust": "Максимальна тяга",
        "crit_max_time": "Максимальний час",
        "crit_min_current": "Мінімальний струм",
        "crit_max_eff": "Максимальна ефективність",
        "crit_compatibility": "Найкраща сумісність",
        "crit_min_mass": "Мінімальна маса",
        "name": "Назва",
        "torque": "Момент",
        "time": "Час",
        "recommended_voltage": "Рекомендована напруга",
        "rpm_margin": "Запас RPM",
        "confidence": "Достовірність",
        "source": "Джерело",
        "frame_structure": "КОНСТРУКЦІЯ РАМИ",
        "frame_checks": "ПЕРЕВІРКИ ТА 3 РЕКОМЕНДАЦІЇ",
        "frame_size_preset": "Стандартний розмір",
        "custom_frame_size": "Власний розмір",
        "frame_diagonal": "Діагональ / розмір",
        "frame_geometry": "Геометрія",
        "frame_motors": "Кількість моторів",
        "arm_width": "Ширина променя",
        "arm_thickness": "Товщина променя",
        "frame_material": "Матеріал",
        "frame_mass": "Маса рами",
        "open_calculation": "ВІДКРИТИЙ РОЗРАХУНОК",
        "open_calculation_info": "Формули та проміжні значення поточної точки можна вручну перевірити звичайним калькулятором.",
        "recalculate": "ПЕРЕРАХУВАТИ",
        "variable": "Змінна",
        "formula": "Формула",
        "value": "Значення",
        "unit": "Одиниця",
        "author": "АВТОР",
        "working_database": "Робоча база даних",
        "offline_subtitle": "ЛАБОРАТОРІЯ СИЛОВИХ УСТАНОВОК - ОФЛАЙН-БАЗА",
        "ready_status": "ГОТОВО",
        "calculation_error": "Помилка розрахунку",
        "delete_confirm": "Видалити вибрану збірку?",
        "import_failed": "Імпорт не виконано",
        "exported": "Експортовано",
        "simple_summary": "Підказка: для польоту перевірте T/W, струм, час роботи та всі червоні попередження. Інженерний режим показує ліміти й повні криві.",
        "source_vs_math": "ДАНІ ДЖЕРЕЛА ТА МАТЕМАТИЧНИЙ РЕЗУЛЬТАТ",
        "source_math_note": "У режимі «Відтворити випробування з бази» обидва рядки використовують однакові RPM та J: перший показує значення початкового файла, другий незалежно перевіряє їх за Ct/Cp і формулами. У режимі «Власні параметри» перший рядок є найближчою базовою характеристикою для порівняння. Тяга та механічна потужність тут завжди для одного пропелера/мотора.",
        "database_preset_status": "З ДЖЕРЕЛА: RPM {rpm}, J {j}, Ct/Cp і швидкість — {source}. ПОХІДНА РЕКОМЕНДАЦІЯ, НЕ ПАРАМЕТРИ ТЕСТУ: тип батареї, S, напруга, KV, C-рейтинг і ESC. Маса, кількість моторів та ємність — параметри апарата.",
        "database_preset_missing": "Для цієї моделі немає повної вихідної характеристики RPM/J/Ct/Cp; використовуйте режим «Власні параметри».",
        "custom_preset_status": "ВЛАСНІ ПАРАМЕТРИ: RPM визначається моделлю мотор–напруга–газ. Щоб точно відтворити опубліковане випробування, виберіть «Відтворити випробування з бази» та потрібну вихідну характеристику.",
        "comparison_no_raw": "Немає повної сирої точки для прямого порівняння.",
        "comparison_explanation": "RPM: база {raw_rpm}, математика {math_rpm} (×{ratio}). Оскільки P=Cp·ρ·n³·D⁵, сам масштаб RPM дає приблизно ×{factor}. Потужність пропелера: {raw_power} → {math_power} на мотор ({delta}%). Верхня картка {total_power} — орієнтовна сумарна ЕЛЕКТРИЧНА потужність для {motors} моторів, тому її не можна напряму порівнювати з механічною потужністю одного пропелера.",
        "raw_database": "Вихідна характеристика бази",
        "math_result": "Математичний розрахунок",
        "method": "Метод",
        "raw_source": "Початковий рядок файла",
        "build_guide": "ЩО САМЕ ВВОДИТИ",
        "build_name_hint": "Наприклад: Survey Quad 15x5.5 - 6S",
        "motor_name_hint": "Точний виробник і модель, наприклад T-Motor MN4014-400KV",
        "battery_name_hint": "Хімія, S, ємність і модель, наприклад LiPo 6S 10000 mAh 25C",
        "esc_name_hint": "Модель і тривалий струм, наприклад Hobbywing 60A OPTO",
        "frame_name_hint": "Модель/тип і розмір рами, наприклад Carbon X 650 mm",
        "description_hint": "Призначення апарата, умови польоту, цільова швидкість і особливі вимоги.",
        "note_hint": "Результат стенду, температура, обмеження, дата зміни або інша службова примітка.",
        "full_guide": "Повний опис",
        "example_1": "Приклад 1 — дані бази",
        "example_2": "Приклад 2 — власна збірка",
        "load_example": "ЗАВАНТАЖИТИ ПРИКЛАД У КАЛЬКУЛЯТОР",
    },
    "en": {
        "calculator": "Calculator",
        "database": "Database",
        "builds": "Saved builds",
        "compare": "Comparison",
        "frame": "Frame",
        "testing": "Formula verification",
        "help": "Methodology",
        "about": "About",
        "simple_mode": "Simple mode",
        "engineering_mode": "Engineering mode",
        "simple_intro": "Quick power-system sizing with only required inputs and the key results.",
        "engineering_intro": "Full engineering model with motor parameters, all margins, sweep and load charts.",
        "calculate": "CALCULATE",
        "add_compare": "Add to comparison",
        "search": "Search",
        "import": "Import",
        "export": "Export propellers.db",
        "basic": "CORE CONFIGURATION",
        "advanced": "ENGINEERING MODEL PARAMETERS",
        "results": "CALCULATION RESULTS",
        "warnings": "WARNINGS AND LIMITATIONS",
        "efficiency": "EFFICIENCY AND OPTIMUM POINT",
        "load_graphs": "LOAD CHARTS",
        "graph_note": "Curves are calculated for 10-100% throttle with the current model, voltage, speed and medium. Yellow vertical line is current throttle; dashed lines are component limits.",
        "hover_help": "Parameter guidance appears here on hover or focus. The ? button opens the full explanation.",
        "help_panel": "CONTEXT HELP",
        "language": "LANGUAGE",
        "units": "UNITS",
        "tooltips": "HOVER TOOLTIPS",
        "configuration_mode": "Operating mode",
        "database_point_mode": "Reproduce a database test",
        "custom_mode": "Custom inputs",
        "reference_point": "Database test condition",
        "model": "Propeller model",
        "medium": "Medium",
        "voltage": "Loaded voltage",
        "throttle": "Throttle",
        "kv": "Motor KV",
        "speed": "Flow speed",
        "mass": "All-up mass",
        "motors": "Motor count",
        "esc": "ESC limit",
        "battery_type": "Battery chemistry",
        "capacity": "Battery capacity",
        "c_rating": "Battery C-rating",
        "battery_s": "Battery cells",
        "rm": "Winding resistance Rm",
        "i0": "No-load current I0",
        "motor_max_current": "Motor maximum current",
        "motor_max_power": "Motor maximum power",
        "density": "Medium density",
        "thrust_card": "THRUST",
        "current_card": "CURRENT",
        "power_card": "POWER",
        "total_current_card": "TOTAL CURRENT",
        "total_power_card": "TOTAL ELECTRICAL POWER",
        "thrust_per_motor": "THRUST / MOTOR",
        "prop_power_per_motor": "PROPELLER POWER / MOTOR",
        "rpm_card": "RPM",
        "tw_card": "THRUST / WEIGHT",
        "runtime_card": "RUNTIME",
        "esc_margin_card": "ESC MARGIN",
        "motor_margin_card": "MOTOR MARGIN",
        "battery_margin_card": "BATTERY MARGIN",
        "structural_card": "STRUCTURAL RPM",
        "confidence_card": "CONFIDENCE",
        "evidence_card": "EVIDENCE",
        "aero_eff": "Aerodynamic efficiency",
        "system_eff": "Powertrain efficiency",
        "optimum": "Optimum point",
        "no_optimum": "No valid sweep point under the specified limits.",
        "no_warnings": "No critical warnings.",
        "simplified": "SIMPLIFIED-MODEL ESTIMATE",
        "chart_thrust": "Thrust vs throttle",
        "chart_current": "Current vs throttle",
        "chart_power": "Electrical power",
        "chart_rpm": "RPM and structural limit",
        "chart_efficiency": "Efficiency vs throttle",
        "throttle_axis": "Throttle, %",
        "thrust_axis": "Thrust",
        "current_axis": "Current, A",
        "power_axis": "Power",
        "rpm_axis": "RPM",
        "efficiency_axis": "Efficiency, %",
        "current_point": "Calculated curve",
        "aerodynamic": "Aerodynamic",
        "powertrain": "Powertrain",
        "esc_limit": "ESC limit",
        "battery_limit": "Battery limit",
        "motor_limit": "Motor limit",
        "structural_limit": "Structural limit",
        "models": "MODELS",
        "characteristics": "CHARACTERISTICS",
        "sources": "SOURCES",
        "real_tests": "REAL TESTS",
        "prediction_only": "PREDICTION ONLY",
        "model_search_placeholder": "Model_ID, original name, manufacturer, series or SKU",
        "characteristics_title": "CHARACTERISTICS OF THE SELECTED MODEL",
        "point_filter_placeholder": "Filter: RPM, J, Ct, Cp, efficiency, class or source file",
        "original": "Original name",
        "manufacturer": "Manufacturer",
        "size": "Diameter x pitch",
        "evidence": "Evidence",
        "points": "Points",
        "geometry": "Geometry",
        "source_file": "Source file",
        "class": "Class",
        "save": "Save build",
        "update": "Update build",
        "save_as": "Save as new",
        "delete": "Delete",
        "duplicate": "Duplicate",
        "clear": "Clear",
        "recommend": "Calculate and recommend",
        "custom_build": "CUSTOM BUILD",
        "build_name": "Name",
        "motor_name": "Motor",
        "battery_name": "Battery",
        "esc_name": "ESC",
        "frame_name": "Frame",
        "payload": "Payload",
        "description": "Description",
        "note": "Note",
        "build_capture_note": "Propeller, KV, battery, ESC, motor count, mass and engineering parameters are captured from the calculator.",
        "saved_builds_list": "SAVED VARIANTS",
        "modules_title": "BUILD MODULES AND ACCESSORIES",
        "modules_note": "Select the modules actually installed, then enter model, quantity and per-item mass. They are stored with the build and affect the physical calculation only through all-up mass.",
        "module_included": "In",
        "module_type": "Type",
        "module_model": "Manufacturer / model",
        "module_quantity": "Qty",
        "module_mass_each": "Mass each",
        "module_mass_total": "Total",
        "module_add_other": "Add other",
        "module_remove": "Remove row",
        "module_reset": "Default list",
        "module_apply_payload": "Apply mass to calculation",
        "module_total": "Selected modules: {count}. Total mass: {mass} {unit}. Do not add it again when it is already included in all-up mass.",
        "module_count": "Modules",
        "module_mass": "Module mass",
        "module_flight_controller": "Flight controller / autopilot",
        "module_power_distribution": "PDB / power board",
        "module_receiver": "RC receiver",
        "module_gps": "GPS / GNSS",
        "module_telemetry": "Telemetry / radio modem",
        "module_vtx": "Video transmitter (VTX)",
        "module_antenna": "Antenna",
        "module_camera": "Camera",
        "module_gimbal": "Camera gimbal",
        "module_remote_id": "Remote ID / identification module",
        "module_sensors": "Sensors",
        "module_landing_gear": "Landing gear",
        "module_wiring": "Wiring, connectors, fasteners",
        "module_other": "Other module",
        "export_json": "Export JSON",
        "import_json": "Import JSON",
        "criterion": "Ranking criterion",
        "crit_max_thrust": "Maximum thrust",
        "crit_max_time": "Maximum runtime",
        "crit_min_current": "Minimum current",
        "crit_max_eff": "Maximum efficiency",
        "crit_compatibility": "Best compatibility",
        "crit_min_mass": "Minimum mass",
        "name": "Name",
        "torque": "Torque",
        "time": "Time",
        "recommended_voltage": "Recommended voltage",
        "rpm_margin": "RPM margin",
        "confidence": "Confidence",
        "source": "Source",
        "frame_structure": "FRAME STRUCTURE",
        "frame_checks": "CHECKS AND 3 RECOMMENDATIONS",
        "frame_size_preset": "Standard size",
        "custom_frame_size": "Custom size",
        "frame_diagonal": "Diagonal / size",
        "frame_geometry": "Geometry",
        "frame_motors": "Motor count",
        "arm_width": "Arm width",
        "arm_thickness": "Arm thickness",
        "frame_material": "Material",
        "frame_mass": "Frame mass",
        "open_calculation": "OPEN CALCULATION TRACE",
        "open_calculation_info": "Formulas and intermediate values of the current point can be checked manually with an ordinary calculator.",
        "recalculate": "RECALCULATE",
        "variable": "Variable",
        "formula": "Formula",
        "value": "Value",
        "unit": "Unit",
        "author": "AUTHOR",
        "working_database": "Working database",
        "offline_subtitle": "PROPULSION SYSTEMS LAB - OFFLINE DATABASE",
        "ready_status": "READY",
        "calculation_error": "Calculation error",
        "delete_confirm": "Delete the selected build?",
        "import_failed": "Import failed",
        "exported": "Exported",
        "simple_summary": "Tip: for flight, verify T/W, current, runtime and every red warning. Engineering mode shows the limits and full curves.",
        "source_vs_math": "SOURCE DATA AND MATHEMATICAL RESULT",
        "source_math_note": "In “Reproduce a database test” mode both rows use identical RPM and J: the first shows the original-file values and the second independently checks them from Ct/Cp and the equations. With “Custom inputs”, the first row is the nearest database characteristic for comparison. Thrust and shaft power here are always per propeller/motor.",
        "database_preset_status": "FROM SOURCE: RPM {rpm}, J {j}, Ct/Cp and speed — {source}. DERIVED RECOMMENDATION, NOT TEST PARAMETERS: battery chemistry, S, voltage, KV, C-rating and ESC. Mass, motor count and capacity remain aircraft inputs.",
        "database_preset_missing": "This model has no complete RPM/J/Ct/Cp database characteristic; use Custom inputs.",
        "custom_preset_status": "CUSTOM INPUTS: RPM is solved from the motor–voltage–throttle model. To reproduce a published test exactly, choose “Reproduce a database test” and the required database test condition.",
        "comparison_no_raw": "No complete raw source point is available for a direct comparison.",
        "comparison_explanation": "RPM: source {raw_rpm}, math {math_rpm} (×{ratio}). Because P=Cp·ρ·n³·D⁵, RPM scaling alone contributes about ×{factor}. Propeller shaft power: {raw_power} → {math_power} per motor ({delta}%). The upper {total_power} card is estimated TOTAL ELECTRICAL power for {motors} motors, so it is not directly comparable to one propeller's shaft power.",
        "raw_database": "Original database characteristic",
        "math_result": "Mathematical calculation",
        "method": "Method",
        "raw_source": "Original file row",
        "build_guide": "WHAT TO ENTER",
        "build_name_hint": "Example: Survey Quad 15x5.5 - 6S",
        "motor_name_hint": "Exact manufacturer and model, e.g. T-Motor MN4014-400KV",
        "battery_name_hint": "Chemistry, S, capacity and model, e.g. LiPo 6S 10000 mAh 25C",
        "esc_name_hint": "Model and continuous current, e.g. Hobbywing 60A OPTO",
        "frame_name_hint": "Frame model/type and size, e.g. Carbon X 650 mm",
        "description_hint": "Aircraft purpose, operating conditions, target speed and special requirements.",
        "note_hint": "Bench result, temperature, limitations, revision date or another service note.",
        "full_guide": "Full guide",
        "example_1": "Example 1 — database data",
        "example_2": "Example 2 — custom build",
        "load_example": "LOAD EXAMPLE INTO CALCULATOR",
    },
}


FIELD_HELP: dict[str, tuple[str, str]] = {
    "configuration_mode": (
        "Що: спосіб визначення робочого режиму. «Відтворити випробування з бази» фіксує RPM і J конкретного рядка початкового тесту; «Власні параметри» визначає RPM із KV, напруги, газу та моторної моделі.\nНавіщо: перший режим потрібен для перевірки опублікованого тесту, другий — для проєктування власного апарата.\nВплив: ручна зміна робочого параметра автоматично вмикає власні параметри.\nКритичність: дуже висока.",
        "What: how the operating condition is determined. “Reproduce a database test” locks RPM and J to one original test row; “Custom inputs” solves RPM from KV, voltage, throttle and the motor model.\nPurpose: use the first to verify a published test and the second to design your own aircraft.\nEffect: manually editing an operating input switches to Custom inputs.\nCriticality: very high."),
    "reference_point": (
        "Що: одна конкретна вихідна характеристика пропелера з початкового файла — RPM, J, Ct і Cp.\nНавіщо: дозволяє точно повторити умови стендового рядка й окремо перевірити тягу та механічну потужність формулами.\nДе знайти: список безпосередньо сформований із бази; фізичні експерименти показані першими.\nНе містить: модель мотора, батарею, ESC або масу апарата, якщо автор джерела їх не опублікував.\nКритичність: дуже висока для перевірки джерела; для власного проєкту виберіть «Власні параметри».",
        "What: one exact propeller characteristic from the original file — RPM, J, Ct and Cp.\nPurpose: reproduces the bench row and independently checks thrust and shaft power with equations.\nWhere: populated directly from the database; physical experiments are listed first.\nDoes not contain: motor, battery, ESC or aircraft mass unless the source author published them.\nCriticality: very high for source verification; choose Custom inputs for your own design."),
    "model": (
        "Що: нормалізований Model_ID пропелера.\nДе знайти: маркування на лопаті або упаковці.\nВплив: більший діаметр зазвичай підвищує тягу й навантаження; більший крок - швидкість і струм.\nТипово: 2-40 in для БПЛА.\nФормула: D входить у T=Ct*rho*n²*D⁴ і P=Cp*rho*n³*D⁵.\nКритичність: дуже висока.",
        "What: normalized propeller Model_ID.\nWhere: blade or package marking.\nEffect: larger diameter usually raises thrust/load; more pitch raises speed and current.\nTypical: 2-40 in for UAVs.\nFormula: D appears in T=Ct*rho*n²*D⁴ and P=Cp*rho*n³*D⁵.\nCriticality: very high."),
    "medium": (
        "Що: робоче середовище - повітря або вода.\nДе знайти: умови застосування.\nВплив: густина прямо масштабує тягу й потужність.\nТипово: повітря 1.225 kg/m³; вода близько 997 kg/m³.\nФормула: T і P пропорційні rho.\nКритичність: дуже висока; у воді кавітація не моделюється.",
        "What: operating medium - air or water.\nWhere: application conditions.\nEffect: density scales thrust and power directly.\nTypical: air 1.225 kg/m³; water about 997 kg/m³.\nFormula: T and P are proportional to rho.\nCriticality: very high; water cavitation is not modeled."),
    "voltage": (
        "Що: фактична напруга батареї під навантаженням.\nДе знайти: телеметрія або S*Uкомірки як номінальна оцінка: LiPo 3.7 V, Li-ion 3.6 V, LiFePO4 3.2 V.\nЗбільшення: вищі RPM, тяга, струм і нагрів. Зменшення: протилежний ефект.\nТипово: 6.4-44.4 V.\nФормула: RPM0=KV*U*газ.\nКритичність: висока.",
        "What: actual loaded battery voltage.\nWhere: telemetry or S*cell voltage nominally: LiPo 3.7 V, Li-ion 3.6 V, LiFePO4 3.2 V.\nIncrease: higher RPM, thrust, current and heat; decrease does the opposite.\nTypical: 6.4-44.4 V.\nFormula: RPM0=KV*V*throttle.\nCriticality: high."),
    "throttle": (
        "Що: команда ESC від 0 до 100%.\nДе знайти: робоча точка польоту або стенду.\nЗбільшення: різко підвищує потужність і навантаження; зменшення збільшує час роботи.\nТипово: 30-100%.\nФормула: Ueff приблизно U*газ; P приблизно RPM³.\nКритичність: висока.",
        "What: ESC command from 0 to 100%.\nWhere: intended flight or bench operating point.\nIncrease: sharply raises power and load; decrease extends runtime.\nTypical: 30-100%.\nFormula: Veff approximately V*throttle; P approximately RPM³.\nCriticality: high."),
    "kv": (
        "Що: оберти мотора на вольт без навантаження.\nДе знайти: паспорт або маркування мотора.\nЗбільшення: вищі RPM і струм; зменшення краще підходить великим пропелерам.\nТипово: 100-3000 RPM/V.\nФормула: RPM0=KV*Ueff; Kt=60/(2*pi*KV).\nКритичність: дуже висока.",
        "What: no-load motor RPM per volt.\nWhere: motor datasheet or marking.\nIncrease: higher RPM/current; decrease better suits large propellers.\nTypical: 100-3000 RPM/V.\nFormula: RPM0=KV*Veff; Kt=60/(2*pi*KV).\nCriticality: very high."),
    "speed": (
        "Що: швидкість потоку відносно пропелера.\nДе знайти: розрахункова швидкість польоту або водного руху.\nЗбільшення: підвищує J і зміщує точку по кривій; 0 означає статику.\nТипово: 0-50 m/s для малих БПЛА.\nФормула: J=V/(n*D).\nКритичність: висока у русі.",
        "What: flow speed relative to the propeller.\nWhere: intended airspeed or water speed.\nIncrease: raises J and moves along the curve; 0 is static.\nTypical: 0-50 m/s for small UAVs.\nFormula: J=V/(n*D).\nCriticality: high in motion."),
    "mass": (
        "Що: повна злітна маса з батареєю та корисним навантаженням.\nДе знайти: зважити готовий апарат.\nЗбільшення: зменшує T/W і запас тяги; зменшення покращує їх.\nТипово: 0.1-25 kg.\nФормула: T/W=Ttotal/(m*g).\nКритичність: дуже висока.",
        "What: all-up mass including battery and payload.\nWhere: weigh the complete aircraft.\nIncrease: lowers T/W and thrust margin; decrease improves them.\nTypical: 0.1-25 kg.\nFormula: T/W=Ttotal/(m*g).\nCriticality: very high."),
    "motors": (
        "Що: кількість однакових мотор-пропелерних вузлів.\nДе знайти: схема апарата.\nЗбільшення: множить загальну тягу, струм і потужність.\nТипово: 1-12.\nФормула: Ttotal=Tmotor*N; Itotal=Imotor*N.\nКритичність: висока.",
        "What: number of identical motor-propeller units.\nWhere: aircraft layout.\nIncrease: multiplies total thrust, current and power.\nTypical: 1-12.\nFormula: Ttotal=Tmotor*N; Itotal=Imotor*N.\nCriticality: high."),
    "esc": (
        "Що: тривалий допустимий струм одного ESC.\nДе знайти: паспорт ESC; не використовуйте короткочасний burst як постійний.\nЗбільшення: лише підвищує запас, не створює тягу.\nТипово: 10-200 A.\nФормула запасу: (Ilimit-I)/Ilimit.\nКритичність: дуже висока.",
        "What: continuous current rating of one ESC.\nWhere: ESC datasheet; do not use burst rating as continuous.\nIncrease: only raises margin, not thrust.\nTypical: 10-200 A.\nMargin formula: (Ilimit-I)/Ilimit.\nCriticality: very high."),
    "battery_type": (
        "Що: хімія акумуляторних комірок.\nДе знайти: етикетка або паспорт батареї.\nВплив: задає номінальну напругу комірки, корисну частку ємності та типовий C-рейтинг. LiPo: 3.7 V/комірку; Li-ion: 3.6 V; LiFePO4: 3.2 V.\nЗбільшення/зменшення: порівнюйте за реальною кількістю S і напругою, а не лише назвою.\nФормула: Unom=S·Ucell; t=usable_fraction·Ah/I.\nКритичність: висока.",
        "What: battery-cell chemistry.\nWhere: battery label or datasheet.\nEffect: sets nominal cell voltage, usable capacity fraction and a typical C-rating. LiPo: 3.7 V/cell; Li-ion: 3.6 V; LiFePO4: 3.2 V.\nIncrease/decrease: compare using the actual S count and voltage, not chemistry name alone.\nFormula: Vnom=S·Vcell; t=usable_fraction·Ah/I.\nCriticality: high."),
    "capacity": (
        "Що: номінальна ємність батареї.\nДе знайти: етикетка батареї або вимір циклу.\nЗбільшення: довший час, але зазвичай більша маса.\nТипово: 0.5-30 Ah.\nФормула: t=0.8*Ah/Itotal*60 min.\nКритичність: середня-висока.",
        "What: nominal battery capacity.\nWhere: battery label or measured cycle.\nIncrease: longer runtime but usually more mass.\nTypical: 0.5-30 Ah.\nFormula: t=0.8*Ah/Itotal*60 min.\nCriticality: medium-high."),
    "c_rating": (
        "Що: заявлена кратність допустимого струму батареї.\nДе знайти: етикетка; реальна здатність старої батареї може бути нижча.\nЗбільшення: підвищує розрахунковий струмовий запас.\nТипово: 10-100 C.\nФормула: Imax=Ah*C.\nКритичність: висока.",
        "What: stated battery discharge multiplier.\nWhere: label; an aged battery may deliver less.\nIncrease: raises calculated current margin.\nTypical: 10-100 C.\nFormula: Imax=Ah*C.\nCriticality: high."),
    "battery_s": (
        "Що: кількість послідовних комірок вибраної хімії.\nДе знайти: маркування батареї.\nЗбільшення: підвищує напругу та можливі RPM; зменшення знижує навантаження.\nТипово: 2-12S.\nФормула: Unom=S*Uкомірки; програма автоматично оновлює номінальну напругу.\nКритичність: дуже висока.",
        "What: number of series cells of the selected chemistry.\nWhere: battery marking.\nIncrease: raises voltage and possible RPM; decrease lowers load.\nTypical: 2-12S.\nFormula: Vnom=S*Vcell; the program updates nominal voltage automatically.\nCriticality: very high."),
    "rm": (
        "Що: опір обмотки мотора.\nДе знайти: моторна карта або 4-провідне вимірювання.\nЗбільшення: більше I²R-втрат і нагріву; зменшення покращує ККД.\nТипово: 0.005-0.5 ohm.\nФормула: I=(Ueff-RPM/KV)/Rm.\nКритичність: висока для точної моделі; порожнє поле вмикає спрощену оцінку.",
        "What: motor winding resistance.\nWhere: motor map or four-wire measurement.\nIncrease: more I²R loss and heat; decrease improves efficiency.\nTypical: 0.005-0.5 ohm.\nFormula: I=(Veff-RPM/KV)/Rm.\nCriticality: high for an accurate model; blank enables simplified estimation."),
    "i0": (
        "Що: струм мотора без навантаження при заданій напрузі.\nДе знайти: паспорт або стенд.\nЗбільшення: більші механічні й магнітні втрати; зменшення покращує ККД.\nТипово: 0.2-8 A.\nФормула: втрати холостого ходу приблизно U*I0.\nКритичність: висока для точної моделі.",
        "What: motor no-load current at the stated voltage.\nWhere: datasheet or bench.\nIncrease: more mechanical/magnetic loss; decrease improves efficiency.\nTypical: 0.2-8 A.\nFormula: no-load loss approximately V*I0.\nCriticality: high for an accurate model."),
    "motor_max_current": (
        "Що: тривалий допустимий струм одного мотора.\nДе знайти: паспорт або теплова стендова карта.\nЗбільшення: підвищує допустимий запас, але не змінює робочу точку.\nТипово: 5-200 A.\nФормула запасу: (Imax-I)/Imax.\nКритичність: дуже висока.",
        "What: continuous current limit of one motor.\nWhere: datasheet or thermal bench map.\nIncrease: raises allowed margin but does not change the operating point.\nTypical: 5-200 A.\nMargin formula: (Imax-I)/Imax.\nCriticality: very high."),
    "motor_max_power": (
        "Що: тривала допустима механічна/електрична потужність мотора за паспортом.\nДе знайти: паспорт із зазначеним охолодженням.\nЗбільшення: підвищує допустимий запас.\nТипово: 50 W-20 kW.\nКритичність: висока; стендова температура важливіша за число в каталозі.",
        "What: continuous motor mechanical/electrical power rating.\nWhere: datasheet with cooling conditions.\nIncrease: raises allowed margin.\nTypical: 50 W-20 kW.\nCriticality: high; bench temperature matters more than a catalog number."),
    "density": (
        "Що: густина робочого середовища.\nДе знайти: стандартна атмосфера або розрахунок за температурою/тиском.\nЗбільшення: прямо підвищує тягу та потрібну потужність.\nТипово: повітря 0.9-1.3 kg/m³; вода 990-1030 kg/m³.\nФормула: T=Ct*rho*n²*D⁴.\nКритичність: висока.",
        "What: operating-medium density.\nWhere: standard atmosphere or temperature/pressure calculation.\nIncrease: directly raises thrust and required power.\nTypical: air 0.9-1.3 kg/m³; water 990-1030 kg/m³.\nFormula: T=Ct*rho*n²*D⁴.\nCriticality: high."),
    "build_name": (
        "Введіть коротку унікальну назву, за якою легко знайти конфігурацію. Бажано включити тип апарата, розмір пропелера та батарею. Приклад: Survey Quad 15x5.5 - 6S.",
        "Enter a short unique name that makes the configuration easy to find. Include aircraft type, propeller size and battery when useful. Example: Survey Quad 15x5.5 - 6S."),
    "motor_name": (
        "Введіть точного виробника й модель мотора, а не лише KV. Приклад: T-Motor MN4014-400KV. Числові KV, Rm, I0 і ліміти вводяться у калькуляторі.",
        "Enter the exact motor manufacturer and model, not KV alone. Example: T-Motor MN4014-400KV. Numeric KV, Rm, I0 and limits are entered in the calculator."),
    "battery_name": (
        "Введіть хімію, кількість S, ємність і модель/бренд. Приклад: LiPo 6S 10000 mAh 25C. Числові S, Ah і C беруться з калькулятора.",
        "Enter chemistry, cell count, capacity and model/brand. Example: LiPo 6S 10000 mAh 25C. Numeric S, Ah and C are captured from the calculator."),
    "esc_name": (
        "Введіть точну модель ESC і його тривалий струм. Приклад: Hobbywing 60A OPTO. Не плутайте постійний ліміт із короткочасним burst.",
        "Enter the exact ESC model and continuous current. Example: Hobbywing 60A OPTO. Do not confuse continuous rating with burst rating."),
    "frame_name": (
        "Введіть модель або тип рами, геометрію і розмір. Приклад: Carbon X 650 mm. Детальну геометрію можна перевірити на вкладці «Рама».",
        "Enter frame model/type, geometry and size. Example: Carbon X 650 mm. Detailed geometry can be checked on the Frame tab."),
    "build_payload": (
        "Маса корисного вантажу без маси самої рами, батареї та силової установки. Введіть у показаній біля поля одиниці. Приклад: камера й підвіс 0.65 kg.",
        "Payload mass excluding the frame, battery and power system. Enter it in the unit shown beside the field. Example: camera and gimbal 0.65 kg."),
    "frame_size_preset": (
        "Що: типовий клас рами за відстанню між осями найдальших моторів.\nДе знайти: маркування рами (наприклад 250, 450 або 650 мм).\nВплив: визначає допустимий діаметр пропелера та довжину променя.\nВиберіть «Власний розмір», якщо конструкція нестандартна.\nКритичність: висока.",
        "What: standard frame class measured between the farthest motor axes.\nWhere: frame marking such as 250, 450 or 650 mm.\nEffect: determines propeller clearance and arm length.\nChoose Custom size for a non-standard structure.\nCriticality: high."),
    "frame_diagonal": (
        "Що: відстань між осями найдальших моторів, не зовнішній габарит рами.\nДе знайти: креслення або вимірювання центр–центр.\nЗбільшення: дозволяє більший пропелер, але збільшує прогин і масу.\nФормула для X/+: відстань сусідніх осей приблизно diagonal/√2.\nКритичність: висока.",
        "What: distance between the farthest motor axes, not the frame's outer dimension.\nWhere: drawing or center-to-center measurement.\nIncrease: allows a larger propeller but increases deflection and mass.\nFor X/+: adjacent-axis spacing is approximately diagonal/√2.\nCriticality: high."),
}


BUILD_GUIDE = {
    "uk": """<h3>Заповнення картки збірки</h3>
    <p><b>Збірка</b> — це ваш збережений варіант усього апарата, а не окремий розрахунок пропелера.</p>
    <p><b>Назва:</b> унікальна зрозуміла назва. <b>Мотор, батарея, ESC і рама:</b> точні виробники та моделі; числові KV, Rm, I0, S, Ah, C, ліміти, маса й пропелер автоматично беруться з поточного калькулятора.</p>
    <p><b>Корисне навантаження:</b> вантаж, який не був включений у повну масу. <b>Опис:</b> призначення, цільовий режим і вимоги. <b>Примітка:</b> стендові результати, температура, дата й обмеження.</p>
    <p><b>Модулі та аксесуари:</b> позначте польотний контролер, PDB, приймач, GPS, телеметрію, VTX, антени, камеру, підвіс, Remote ID, датчики, шасі, проводку та інше. Вкажіть кількість і масу одного. Вони зберігаються як повний склад; у фізичному розрахунку впливають лише через масу.</p>
    <p style='color:#6FD3C6'><b>Порядок:</b> 1) розрахуйте режим у калькуляторі; 2) заповніть назви; 3) позначте модулі; 4) якщо їх маса ще не врахована — натисніть «Врахувати масу в розрахунку»; 5) збережіть. Повторне натискання оновлює, а не дублює цю масу.</p>""",
    "en": """<h3>Completing the build card</h3>
    <p>A <b>build</b> is your saved whole-aircraft variant, not a standalone propeller calculation.</p>
    <p><b>Name:</b> a unique recognizable name. <b>Motor, battery, ESC and frame:</b> exact manufacturers and models; numeric KV, Rm, I0, S, Ah, C, limits, mass and propeller are captured automatically from the current calculator.</p>
    <p><b>Payload:</b> cargo not already included in all-up mass. <b>Description:</b> purpose, target condition and requirements. <b>Note:</b> bench result, temperature, date and limitations.</p>
    <p><b>Modules and accessories:</b> select flight controller, PDB, receiver, GPS, telemetry, VTX, antennas, camera, gimbal, Remote ID, sensors, landing gear, wiring and other equipment. Enter quantity and per-item mass. They are saved as the complete inventory; physically they affect the calculation only through mass.</p>
    <p style='color:#6FD3C6'><b>Workflow:</b> 1) calculate the intended condition; 2) enter names; 3) select modules; 4) when their mass is not yet included, click “Apply mass to calculation”; 5) save. Repeated clicks update rather than duplicate that mass.</p>""",
}
